version: "3.5"

services:
  main_service:
    container_name: "main_service"
    restart: unless-stopped
    build:
      context: ./../..
      dockerfile: ./mainservice/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - socnet-network
  
  post_service:
    container_name: "post_service"
    restart: unless-stopped
    build:
      context: ./../..
      dockerfile: ./posts_service/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - socnet-network


networks:
  socnet-network:
    name: "socnet-network"